from guia_linux.tools import (
    awk, cat, chmod, chown, crontab, curl, cut, df, docker, du,
    file_descriptors, find, firewall_cmd, free, git, grep, head,
    htop, ifconfig, ip, iptables, jq, logs, lsblk, lsof, lxc,
    nc, netstat, nmap, ps, regex, rsync, scp, sed, shortcuts,
    sort, ss, ssh, system, systemctl, tail, tar, tee, tmux,
    top, tr, uname, uniq, vim, watch, xargs,
)

TOOLS = {
    "awk":         awk,
    "cat":         cat,
    "chmod":       chmod,
    "chown":       chown,
    "crontab":     crontab,
    "curl":        curl,
    "cut":         cut,
    "df":          df,
    "docker":      docker,
    "du":          du,
    "descriptors": file_descriptors,
    "find":        find,
    "firewall-cmd": firewall_cmd,
    "free":        free,
    "git":         git,
    "grep":        grep,
    "head":        head,
    "htop":        htop,
    "ifconfig":    ifconfig,
    "ip":          ip,
    "iptables":    iptables,
    "jq":          jq,
    "logs":        logs,
    "lsblk":       lsblk,
    "lsof":        lsof,
    "lxc":         lxc,
    "nc":          nc,
    "netstat":     netstat,
    "nmap":        nmap,
    "ps":          ps,
    "regex":       regex,
    "rsync":       rsync,
    "scp":         scp,
    "sed":         sed,
    "shortcuts":   shortcuts,
    "sort":        sort,
    "ss":          ss,
    "ssh":         ssh,
    "system":      system,
    "systemctl":   systemctl,
    "tail":        tail,
    "tar":         tar,
    "tee":         tee,
    "tmux":        tmux,
    "top":         top,
    "tr":          tr,
    "uname":       uname,
    "uniq":        uniq,
    "vim":         vim,
    "watch":       watch,
    "xargs":       xargs,
}
